### PR TITLE
Update for purs 0.11.1

### PR DESCRIPTION
**Pull request by mlang**

### CODE REVIEW

**Comment by garyb** [comment]
Thanks! Just looks like the `package.json` dependencies all need bumping too.

**Comment by mlang** [comment]
Did you mean bumping purescript to 0.11.1 or any others as well?

-    "purescript": "^0.10.1",
+    "purescript": "^0.11.1",


I've never used package.json so far.  How do I test this?

**Comment by garyb** [comment]
`pulp` and `purescript-psa` will need updating too. You can just lift the one used here though: https://github.com/garyb/purescript-quickcheck-laws/blob/b502b555574663e54a4d1231afc7038248fb69dc/package.json

Travis will test it for you 😆 - but aside from that, use `npm install` and then try `npm run build` / `npm run test`. Or `yarn` rather than `npm` if you prefer.

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
