### PR TITLE
add Enum and BoundedEnum

### PR DESCRIPTION
**Pull request by safareli**

### CODE REVIEW

**Comment by garyb** [comment]
Do you need to use strongcheck over quickcheck? QC is quite a bit faster and fully stack safe nowadays.

**Comment by safareli** [comment]
Was using it in my old repo will switch to quickcheck

**Comment by garyb** [comment]
👍 I'll merge this too, so thanks! I'd just recommend QC unless you need any of the SC-specific features.

**Comment by safareli** [comment]
Thanks for recommendation!

**Pull request merged**
